// Auto-generated by process-supreme-court-terms-2-10-pdf.js
// DO NOT EDIT MANUALLY - Run script to update

export const supremeCourtRulingsTerms2To10 = [
  {
    id: 'term-2-ruling-001',
    title: 'AdamStratton v. Technozo',
    docketNumber: 'No. 38',
    term: 2,
    date: 'AUGUST 15, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-002',
    title: 'JedBartlett v. Federal Elections Commission',
    docketNumber: 'No. 38',
    term: 2,
    date: 'MAY 14, 2017',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-003',
    title: 'United States v. Las Vegas',
    docketNumber: '39-42',
    term: 2,
    date: 'August 14, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-004',
    title: 'HHPrinceGeorge v. Capitalized',
    docketNumber: 'No. 76',
    term: 2,
    date: 'August 14, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-005',
    title: 'Qolio v. United States',
    docketNumber: '693-694',
    term: 2,
    date: 'November 27, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-006',
    title: 'CodyGamer100 v. United States',
    docketNumber: '88-89',
    term: 2,
    date: 'November 28, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-007',
    title: 'Bob561 v. Mindy_Lahiri',
    docketNumber: '404-405',
    term: 2,
    date: 'December 28, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-008',
    title: 'DonaldJTrump v. United States',
    docketNumber: 'No. 78',
    term: 2,
    date: 'December 29, 2016',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-009',
    title: 'Likeanub v. United States',
    docketNumber: '63-66',
    term: 2,
    date: 'January 13, 2017',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-010',
    title: 'Zeyad567ALT v. SteffJonez',
    docketNumber: '8-9',
    term: 2,
    date: 'January 14, 2017',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-011',
    title: 'Sudden v. Helleoh',
    docketNumber: '344-345',
    term: 2,
    date: 'January 10, 2017',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-012',
    title: 'Ryan_Revan v. United States',
    docketNumber: '68-69',
    term: 2,
    date: 'February 12, 2017',
    court: 'Supreme Court',
    description:
      '2\nAUGUST TERM 2016\nUNITED STATES\nREPORTS\n\n-- 1 of 98 --\n\nUNITED STATES REPORTS\nVOLUME 2\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2016\nAUGUST 15, 2016 THROUGH MAY 14, 2017\nTOGETHER WITH OPIN',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-001',
    title: 'Norman_Paperman v. United States Military',
    docketNumber: 'No. 03',
    term: 3,
    date: 'MAY 15, 2016',
    court: 'Supreme Court',
    description:
      '3\nMAY TERM 2017\nUNITED STATES\nREPORTS\n\n-- 1 of 107 --\n\nUNITED STATES REPORTS\nVOLUME 3\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nMAY TERM, 2017\nMAY 15, 2016 THROUGH AUGUST 14, 2017\nTOGETHER WITH OPINION O',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-002',
    title: 'SigmaHD v. United States Marshals Service',
    docketNumber: 'No. 03',
    term: 3,
    date: 'AUGUST 14, 2017',
    court: 'Supreme Court',
    description:
      '3\nMAY TERM 2017\nUNITED STATES\nREPORTS\n\n-- 1 of 107 --\n\nUNITED STATES REPORTS\nVOLUME 3\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nMAY TERM, 2017\nMAY 15, 2016 THROUGH AUGUST 14, 2017\nTOGETHER WITH OPINION O',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-003',
    title: 'MythicOne v. National Security Agency',
    docketNumber: 'No. 03',
    term: 3,
    date: 'May 16, 2017',
    court: 'Supreme Court',
    description:
      '3\nMAY TERM 2017\nUNITED STATES\nREPORTS\n\n-- 1 of 107 --\n\nUNITED STATES REPORTS\nVOLUME 3\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nMAY TERM, 2017\nMAY 15, 2016 THROUGH AUGUST 14, 2017\nTOGETHER WITH OPINION O',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-004',
    title: 'British2004 v. Ozzymen',
    docketNumber: 'No. 03',
    term: 3,
    date: 'June 4, 2017',
    court: 'Supreme Court',
    description:
      '3\nMAY TERM 2017\nUNITED STATES\nREPORTS\n\n-- 1 of 107 --\n\nUNITED STATES REPORTS\nVOLUME 3\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nMAY TERM, 2017\nMAY 15, 2016 THROUGH AUGUST 14, 2017\nTOGETHER WITH OPINION O',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-005',
    title: 'Idiotic_Leader v. Las Vegas',
    docketNumber: 'No. 07',
    term: 3,
    date: 'June 6, 2017',
    court: 'Supreme Court',
    description:
      '3\nMAY TERM 2017\nUNITED STATES\nREPORTS\n\n-- 1 of 107 --\n\nUNITED STATES REPORTS\nVOLUME 3\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nMAY TERM, 2017\nMAY 15, 2016 THROUGH AUGUST 14, 2017\nTOGETHER WITH OPINION O',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-001',
    title: 'Seaborn v. Lukassie',
    docketNumber: 'No. 04',
    term: 4,
    date: 'August 23, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-002',
    title: '12904 v. Khemists',
    docketNumber: 'No. 04',
    term: 4,
    date: 'September 21, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-003',
    title: 'Snowbleed v. Nevada Highway Patrol',
    docketNumber: 'No. 04',
    term: 4,
    date: 'August 9, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-004',
    title: 'United States v. Las Vegas',
    docketNumber: 'No. 04',
    term: 4,
    date: 'October 18, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-001',
    title: 'In Re United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'August 14, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-002',
    title: 'Dominator v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'February 27, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-003',
    title: 'George v. Troyan',
    docketNumber: 'No. 05',
    term: 5,
    date: 'March 10, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-004',
    title: 'George v. United States',
    docketNumber: '1766-1769',
    term: 5,
    date: 'March 16, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-005',
    title: 'Kirkman v. United States',
    docketNumber: 'No. 21',
    term: 5,
    date: 'March 20, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-006',
    title: 'Nuinik v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'August 2, 2017',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-007',
    title: 'RoExplo v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'March 1, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-008',
    title: 'United States v. District of Columbia',
    docketNumber: 'No. 05',
    term: 5,
    date: 'April 6, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-009',
    title: 'United States v. TPR',
    docketNumber: 'No. 05',
    term: 5,
    date: 'February 27, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-010',
    title: 'Code_Rager v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'April 1, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-011',
    title: 'Kirkman v. Nevada Highway Patrol',
    docketNumber: 'No. 05',
    term: 5,
    date: 'April 6, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-012',
    title: 'Heave v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'March 1, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-013',
    title: 'Ex Parte United States',
    docketNumber: 'No. 89',
    term: 5,
    date: 'March 14, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n5\nFEB. TERM 2018\n\n-- 1 of 143 --\n\nUNITED STATES REPORTS\nVOLUME 5\nCASES ADJUDGED\nin\nTHE SUPREME COURT\nat\nFEBRUARY TERM, 2018\nFebruary 15 Through August 14, 2018\nTIMOTHY F. GEITHNE',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-001',
    title: 'Technozo v. United States',
    docketNumber: 'No. 05',
    term: 6,
    date: 'August 25, 2018',
    court: 'Supreme Court',
    description:
      '6\nAUGUST TERM 2018\nUNITED STATES\nREPORTS\nUNITED STATES REPORTS\n\n-- 1 of 60 --\n\nVOLUME 6\n–—————\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2018\n–—————\nDAVID E. RACINE, III\n–—————\n\n-- 2 of 60 -',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-002',
    title: 'Ultiman v. United States',
    docketNumber: 'No. 05',
    term: 6,
    date: 'August 15, 2018',
    court: 'Supreme Court',
    description:
      '6\nAUGUST TERM 2018\nUNITED STATES\nREPORTS\nUNITED STATES REPORTS\n\n-- 1 of 60 --\n\nVOLUME 6\n–—————\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2018\n–—————\nDAVID E. RACINE, III\n–—————\n\n-- 2 of 60 -',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-003',
    title: 'Benda v. United States',
    docketNumber: 'No. 05',
    term: 6,
    date: 'October 21, 2018',
    court: 'Supreme Court',
    description:
      '6\nAUGUST TERM 2018\nUNITED STATES\nREPORTS\nUNITED STATES REPORTS\n\n-- 1 of 60 --\n\nVOLUME 6\n–—————\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2018\n–—————\nDAVID E. RACINE, III\n–—————\n\n-- 2 of 60 -',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-004',
    title: 'Federal Election Commission v. AcidRaps',
    docketNumber: '85-86',
    term: 6,
    date: 'August 5, 2018',
    court: 'Supreme Court',
    description:
      '6\nAUGUST TERM 2018\nUNITED STATES\nREPORTS\nUNITED STATES REPORTS\n\n-- 1 of 60 --\n\nVOLUME 6\n–—————\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2018\n–—————\nDAVID E. RACINE, III\n–—————\n\n-- 2 of 60 -',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-005',
    title: 'Kirkman v. Bank of America',
    docketNumber: '66-67',
    term: 6,
    date: 'August 26, 2018',
    court: 'Supreme Court',
    description:
      '6\nAUGUST TERM 2018\nUNITED STATES\nREPORTS\nUNITED STATES REPORTS\n\n-- 1 of 60 --\n\nVOLUME 6\n–—————\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2018\n–—————\nDAVID E. RACINE, III\n–—————\n\n-- 2 of 60 -',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-7-ruling-001',
    title: 'Lydxia v. House of Representatives',
    docketNumber: '07-01',
    term: 7,
    date: 'FEBRUARY 15, 2019',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n7\nFEB. TERM2019\n\n-- 1 of 75 --\n\nVOLUME7\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2019\nFEBRUARY 15, 2019 THROUGH AUGUST 13, 2019\nTOGETHER WITH OPINIO N OF INDIV ID UA',
    status: 'Archived',
    url: '/docs/supreme-court/term-7.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-7-ruling-002',
    title: 'Kirkman v. State of Columbia',
    docketNumber: '07-02',
    term: 7,
    date: 'AUGUST 13, 2019',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n7\nFEB. TERM2019\n\n-- 1 of 75 --\n\nVOLUME7\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2019\nFEBRUARY 15, 2019 THROUGH AUGUST 13, 2019\nTOGETHER WITH OPINIO N OF INDIV ID UA',
    status: 'Archived',
    url: '/docs/supreme-court/term-7.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-7-ruling-003',
    title: 'Cursive v. United States',
    docketNumber: '101-104',
    term: 7,
    date: 'March 3, 2019',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n7\nFEB. TERM2019\n\n-- 1 of 75 --\n\nVOLUME7\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2019\nFEBRUARY 15, 2019 THROUGH AUGUST 13, 2019\nTOGETHER WITH OPINIO N OF INDIV ID UA',
    status: 'Archived',
    url: '/docs/supreme-court/term-7.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-7-ruling-004',
    title: 'Party v. Board of Law Examiners',
    docketNumber: '101-104',
    term: 7,
    date: 'April 4, 2019',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n7\nFEB. TERM2019\n\n-- 1 of 75 --\n\nVOLUME7\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2019\nFEBRUARY 15, 2019 THROUGH AUGUST 13, 2019\nTOGETHER WITH OPINIO N OF INDIV ID UA',
    status: 'Archived',
    url: '/docs/supreme-court/term-7.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-7-ruling-005',
    title: 'In Re Haven',
    docketNumber: '884-885',
    term: 7,
    date: 'May 7, 2019',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n7\nFEB. TERM2019\n\n-- 1 of 75 --\n\nVOLUME7\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2019\nFEBRUARY 15, 2019 THROUGH AUGUST 13, 2019\nTOGETHER WITH OPINIO N OF INDIV ID UA',
    status: 'Archived',
    url: '/docs/supreme-court/term-7.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-7-ruling-006',
    title: 'In Re Giordano',
    docketNumber: '1-2',
    term: 7,
    date: 'March 23, 2019',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n7\nFEB. TERM2019\n\n-- 1 of 75 --\n\nVOLUME7\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2019\nFEBRUARY 15, 2019 THROUGH AUGUST 13, 2019\nTOGETHER WITH OPINIO N OF INDIV ID UA',
    status: 'Archived',
    url: '/docs/supreme-court/term-7.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-9-ruling-001',
    title: 'Reset v. United States',
    docketNumber: '235-236',
    term: 9,
    date: 'FEBRUARY 14, 2020',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n9\nFEB. TERM2020\n\n-- 1 of 242 --\n\nVOLUME9\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2020\nFEBRUARY 14, 2020 THROUGH AUGUST 14, 2020\nTOGETHER WITH OPINIO N OF INDIV ID U',
    status: 'Archived',
    url: '/docs/supreme-court/term-9.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-9-ruling-002',
    title: 'Monkey v. United States',
    docketNumber: '234-235',
    term: 9,
    date: 'AUGUST 14, 2020',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n9\nFEB. TERM2020\n\n-- 1 of 242 --\n\nVOLUME9\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2020\nFEBRUARY 14, 2020 THROUGH AUGUST 14, 2020\nTOGETHER WITH OPINIO N OF INDIV ID U',
    status: 'Archived',
    url: '/docs/supreme-court/term-9.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-9-ruling-003',
    title: 'Caldwell v. United States',
    docketNumber: '233-234',
    term: 9,
    date: 'April 20, 2020',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n9\nFEB. TERM2020\n\n-- 1 of 242 --\n\nVOLUME9\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2020\nFEBRUARY 14, 2020 THROUGH AUGUST 14, 2020\nTOGETHER WITH OPINIO N OF INDIV ID U',
    status: 'Archived',
    url: '/docs/supreme-court/term-9.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-9-ruling-004',
    title: 'Kolibob v. United States',
    docketNumber: '232-233',
    term: 9,
    date: 'April 26, 2020',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n9\nFEB. TERM2020\n\n-- 1 of 242 --\n\nVOLUME9\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2020\nFEBRUARY 14, 2020 THROUGH AUGUST 14, 2020\nTOGETHER WITH OPINIO N OF INDIV ID U',
    status: 'Archived',
    url: '/docs/supreme-court/term-9.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-9-ruling-005',
    title: 'Tools v. United States',
    docketNumber: 'No. 09-30',
    term: 9,
    date: 'April 18, 2020',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n9\nFEB. TERM2020\n\n-- 1 of 242 --\n\nVOLUME9\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2020\nFEBRUARY 14, 2020 THROUGH AUGUST 14, 2020\nTOGETHER WITH OPINIO N OF INDIV ID U',
    status: 'Archived',
    url: '/docs/supreme-court/term-9.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-9-ruling-006',
    title: 'Caldwell v. Dream',
    docketNumber: 'No. 09-31',
    term: 9,
    date: 'April 28, 2020',
    court: 'Supreme Court',
    description:
      'UNITED STATES\nREPORTS\n9\nFEB. TERM2020\n\n-- 1 of 242 --\n\nVOLUME9\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nFEBRUARY TERM, 2020\nFEBRUARY 14, 2020 THROUGH AUGUST 14, 2020\nTOGETHER WITH OPINIO N OF INDIV ID U',
    status: 'Archived',
    url: '/docs/supreme-court/term-9.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-001',
    title: 'Psychodynamic v. Technozo',
    docketNumber: '08-0006',
    term: 10,
    date: 'August 14, 2020',
    court: 'Supreme Court',
    description:
      '10\nAUG. TERM 2020\nUNITED STATES\nREPORTS\n\n-- 1 of 122 --\n\nUNITED STATES REPORTS\nVOLUME 10\n–———\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2020\nAugust 14, 2020 Through February 14, 2021\nTogethe',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-002',
    title: 'Rafellus v. Papasbestboy',
    docketNumber: '80-15',
    term: 10,
    date: 'February 14, 2021',
    court: 'Supreme Court',
    description:
      '10\nAUG. TERM 2020\nUNITED STATES\nREPORTS\n\n-- 1 of 122 --\n\nUNITED STATES REPORTS\nVOLUME 10\n–———\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2020\nAugust 14, 2020 Through February 14, 2021\nTogethe',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-003',
    title: 'United States v. jetpacksoup',
    docketNumber: 'No. 09-36',
    term: 10,
    date: 'July 7, 2020',
    court: 'Supreme Court',
    description:
      '10\nAUG. TERM 2020\nUNITED STATES\nREPORTS\n\n-- 1 of 122 --\n\nUNITED STATES REPORTS\nVOLUME 10\n–———\nCASES ADJUDGED\nIN\nTHE SUPREME COURT\nAT\nAUGUST TERM, 2020\nAugust 14, 2020 Through February 14, 2021\nTogethe',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  }
]

export default supremeCourtRulingsTerms2To10
