// Auto-generated by process-supreme-court-terms-2-10-pdf.js
// DO NOT EDIT MANUALLY - Run script to update

export const supremeCourtRulingsTerms2To10 = [
  {
    id: 'term-2-ruling-001',
    title: 'United States v. Las Vegas',
    docketNumber: 'No. 38',
    term: 2,
    date: 'August 14, 2016',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-002',
    title: 'HHPrinceGeorge v. Capitalized',
    docketNumber: 'No. 38',
    term: 2,
    date: 'August 14, 2016',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-003',
    title: 'Qolio v. United States',
    docketNumber: 'No. 76',
    term: 2,
    date: 'November 27, 2016',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-004',
    title: 'CodyGamer100 v. United States',
    docketNumber: 'No. 78',
    term: 2,
    date: 'November 28, 2016',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-005',
    title: 'Bob561 v. Mindy_Lahiri',
    docketNumber: 'No. 78',
    term: 2,
    date: 'January 13, 2017',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-006',
    title: 'Likeanub v. United States',
    docketNumber: 'No. 38',
    term: 2,
    date: 'January 14, 2017',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-007',
    title: 'Zeyad567ALT v. SteffJonez',
    docketNumber: 'No. 38',
    term: 2,
    date: 'January 25, 2017',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-008',
    title: 'AdamStratton v. Technozo',
    docketNumber: 'No. 38',
    term: 2,
    date: 'February 1, 2017',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-009',
    title: 'Sudden v. Helleoh',
    docketNumber: 'No. 38',
    term: 2,
    date: 'April 19, 2015',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-010',
    title: 'Ryan_Revan v. United States',
    docketNumber: 'No. 38',
    term: 2,
    date: 'April 20, 2015',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-2-ruling-011',
    title: 'DonaldJTrump v. United States',
    docketNumber: 'No. 38',
    term: 2,
    date: 'January 29, 2016',
    court: 'Supreme Court',
    description:
      '2 AUGUST TERM 2016 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 2 CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2016 A UGUST 15 , 2016 T HROUGH M AY 1 4, 2017 T OGETHER W ITH O PINION OF I',
    status: 'Archived',
    url: '/docs/supreme-court/term-2.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-001',
    title: 'MythicOne v. National Security Agency',
    docketNumber: 'No. 03',
    term: 3,
    date: 'May 16, 2017',
    court: 'Supreme Court',
    description:
      '3 MAY TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 3 CASES ADJUDGED IN THE SUPREME COURT AT MAY TERM, 2017 M AY 15 , 2016 T HROUGH A UGUST 1 4, 2017 T OGETHER W ITH O PINION OF I NDIV',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-002',
    title: 'British2004 v. Ozzymen',
    docketNumber: 'No. 07',
    term: 3,
    date: 'June 4, 2017',
    court: 'Supreme Court',
    description:
      '3 MAY TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 3 CASES ADJUDGED IN THE SUPREME COURT AT MAY TERM, 2017 M AY 15 , 2016 T HROUGH A UGUST 1 4, 2017 T OGETHER W ITH O PINION OF I NDIV',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-3-ruling-003',
    title: 'Idiotic_Leader v. Las Vegas',
    docketNumber: 'No. 78',
    term: 3,
    date: 'June 6, 2017',
    court: 'Supreme Court',
    description:
      '3 MAY TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 3 CASES ADJUDGED IN THE SUPREME COURT AT MAY TERM, 2017 M AY 15 , 2016 T HROUGH A UGUST 1 4, 2017 T OGETHER W ITH O PINION OF I NDIV',
    status: 'Archived',
    url: '/docs/supreme-court/term-3.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-001',
    title: 'Seaborn v. Lukassie',
    docketNumber: 'No. 04',
    term: 4,
    date: 'August 23, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-002',
    title: '12904 v. Khemists',
    docketNumber: 'No. 04',
    term: 4,
    date: 'September 21, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-003',
    title: 'Snowbleed v. Nevada Highway Patrol',
    docketNumber: 'No. 04',
    term: 4,
    date: 'August 9, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-4-ruling-004',
    title: 'United States v. Las Vegas',
    docketNumber: 'No. 04',
    term: 4,
    date: 'October 18, 2017',
    court: 'Supreme Court',
    description:
      '4 AUGUST TERM 201 7 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 4 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2017 August 15 , 2017 Through February 1 4, 2018 Together With Op',
    status: 'Archived',
    url: '/docs/supreme-court/term-4.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-001',
    title: 'RoExplo v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'August 14, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-002',
    title: 'United States v. TPR',
    docketNumber: 'No. 05',
    term: 5,
    date: 'February 27, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-003',
    title: 'Code_Rager v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'March 10, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-004',
    title: 'Kirkman v. Nevada Highway Patrol',
    docketNumber: '1766-1769',
    term: 5,
    date: 'March 16, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-005',
    title: 'Kirkman v. United States',
    docketNumber: 'No. 21',
    term: 5,
    date: 'March 20, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-006',
    title: 'George v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'August 2, 2017',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-007',
    title: 'Nuinik v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'March 1, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-008',
    title: 'United States v. District of Columbia',
    docketNumber: 'No. 05',
    term: 5,
    date: 'April 6, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-009',
    title: 'George v. Troyan',
    docketNumber: 'No. 05',
    term: 5,
    date: 'February 27, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-010',
    title: 'Dominator v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'April 1, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-011',
    title: 'Heave v. United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'April 6, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-012',
    title: 'Ex Parte United States',
    docketNumber: 'No. 05',
    term: 5,
    date: 'March 1, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-5-ruling-013',
    title: 'In Re United States',
    docketNumber: 'No. 89',
    term: 5,
    date: 'March 14, 2018',
    court: 'Supreme Court',
    description:
      'UNITED STATES REPORTS 5 FEB. TERM 2018 UNITED STATES REPORTS VOLUME 5 CASES ADJUDGED in THE SUPREME COURT at FEBRUARY TERM, 2018 February 15 Through August 14, 2018 TIMOTHY F. GEITHNER reporter of dec',
    status: 'Archived',
    url: '/docs/supreme-court/term-5.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-001',
    title: 'Kirkman v. Bank of America',
    docketNumber: 'No. 05',
    term: 6,
    date: 'August 25, 2018',
    court: 'Supreme Court',
    description:
      '6 AUGUST TERM 201 8 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 6 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2018 – —— —— — DAVID E. RACINE, III – — —— —— JUSTICES SUPREME CO',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-002',
    title: 'Technozo v. United States',
    docketNumber: 'No. 05',
    term: 6,
    date: 'August 15, 2018',
    court: 'Supreme Court',
    description:
      '6 AUGUST TERM 201 8 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 6 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2018 – —— —— — DAVID E. RACINE, III – — —— —— JUSTICES SUPREME CO',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-003',
    title: 'Ultiman v. United States',
    docketNumber: 'No. 05',
    term: 6,
    date: 'October 21, 2018',
    court: 'Supreme Court',
    description:
      '6 AUGUST TERM 201 8 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 6 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2018 – —— —— — DAVID E. RACINE, III – — —— —— JUSTICES SUPREME CO',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-004',
    title: 'Benda v. United States',
    docketNumber: 'No. 05',
    term: 6,
    date: 'August 5, 2018',
    court: 'Supreme Court',
    description:
      '6 AUGUST TERM 201 8 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 6 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2018 – —— —— — DAVID E. RACINE, III – — —— —— JUSTICES SUPREME CO',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-6-ruling-005',
    title: 'Federal Election Commission v. AcidRaps',
    docketNumber: 'No. 06',
    term: 6,
    date: 'August 26, 2018',
    court: 'Supreme Court',
    description:
      '6 AUGUST TERM 201 8 UNITED STATES REPORTS UNITED STATES REPORTS VOLUME 6 – — —— —— CASES ADJUDGED IN THE SUPREME COURT AT AUGUST TERM, 2018 – —— —— — DAVID E. RACINE, III – — —— —— JUSTICES SUPREME CO',
    status: 'Archived',
    url: '/docs/supreme-court/term-6.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-001',
    title: 'Psychodynamic v. Technozo',
    docketNumber: 'No. 09',
    term: 10,
    date: 'July 7, 2020',
    court: 'Supreme Court',
    description:
      '10 AUG. TERM 2020 UNITED STATES REPORTS UNITED STATES REPORT S VOLUME 10 – ——— CASES ADJUDGE D IN THE SUPREME COURT AT AUGUST TERM, 2020 August 14 , 20 20 Thr o ugh February 1 4, 20 2 1 Together With ',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-002',
    title: '12904 v. KingLukassie',
    docketNumber: 'No. 09',
    term: 10,
    date: 'August 10, 2020',
    court: 'Supreme Court',
    description:
      '10 AUG. TERM 2020 UNITED STATES REPORTS UNITED STATES REPORT S VOLUME 10 – ——— CASES ADJUDGE D IN THE SUPREME COURT AT AUGUST TERM, 2020 August 14 , 20 20 Thr o ugh February 1 4, 20 2 1 Together With ',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-003',
    title: 'United States v. jetpacksoup',
    docketNumber: 'No. 09',
    term: 10,
    date: 'August 17, 2020',
    court: 'Supreme Court',
    description:
      '10 AUG. TERM 2020 UNITED STATES REPORTS UNITED STATES REPORT S VOLUME 10 – ——— CASES ADJUDGE D IN THE SUPREME COURT AT AUGUST TERM, 2020 August 14 , 20 20 Thr o ugh February 1 4, 20 2 1 Together With ',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  },
  {
    id: 'term-10-ruling-004',
    title: 'Rafellus v. Papasbestboy',
    docketNumber: 'No. 80',
    term: 10,
    date: 'August 18, 2020',
    court: 'Supreme Court',
    description:
      '10 AUG. TERM 2020 UNITED STATES REPORTS UNITED STATES REPORT S VOLUME 10 – ——— CASES ADJUDGE D IN THE SUPREME COURT AT AUGUST TERM, 2020 August 14 , 20 20 Thr o ugh February 1 4, 20 2 1 Together With ',
    status: 'Archived',
    url: '/docs/supreme-court/term-10.pdf',
    links: [],
    linkCount: 0
  }
]

export default supremeCourtRulingsTerms2To10
